const data = [
    {
        id:"1",
        nombre:"jhon",
        apellido:"romero",
        edad:27
    },
    {
        id:"2",
        nombre:"jhon",
        apellido:"romero",
        edad:27
    },
    {
        id:"3",
        nombre:"jhon",
        apellido:"romero",
        edad:27
    },
    {
        id:"4",
        nombre:"jhon",
        apellido:"romero",
        edad:27
    },
    {
        id:"5",
        nombre:"jhon",
        apellido:"romero",
        edad:27
    },
    {
        id:"6",
        nombre:"jhon",
        apellido:"romero",
        edad:27
    },
    {
        id:"7",
        nombre:"jhon",
        apellido:"romero",
        edad:27
    },
    {
        id:"8",
        nombre:"jhon",
        apellido:"romero",
        edad:27
    },
    {
        id:"9",
        nombre:"jhon",
        apellido:"romero",
        edad:27
    },
    {
        id:"10",
        nombre:"jhon",
        apellido:"romero",
        edad:27
    },
    {
        id:"11",
        nombre:"jhon",
        apellido:"romero",
        edad:27
    },
    {
        id:"12",
        nombre:"jhon",
        apellido:"romero",
        edad:27
    },
    {
        id:"13",
        nombre:"predo",
        apellido:"romero",
        edad:27
    },
    {
        id:"14",
        nombre:"perez",
        apellido:"romero",
        edad:27
    },
    {
        id:"15",
        nombre:"pererira",
        apellido:"romero",
        edad:27
    },
    {
        id:"1",
        nombre:"pobre",
        apellido:"romero",
        edad:27
    },
    {
        id:"1",
        nombre:"pintor",
        apellido:"romero",
        edad:27
    },
    {
        id:"1",
        nombre:"jhon",
        apellido:"romero",
        edad:27
    },
    {
        id:"1",
        nombre:"jhon",
        apellido:"romero",
        edad:27
    },
    {
        id:"1",
        nombre:"jhon",
        apellido:"romero",
        edad:27
    },
    {
        id:"1",
        nombre:"jhon",
        apellido:"romero",
        edad:27
    },
    {
        id:"1",
        nombre:"jhon",
        apellido:"romero",
        edad:27
    },
    {
        id:"1",
        nombre:"jhon",
        apellido:"romero",
        edad:27
    },
    {
        id:"1",
        nombre:"jhon",
        apellido:"romero",
        edad:27
    },
    {
        id:"1",
        nombre:"jhon",
        apellido:"romero",
        edad:27
    },
    {
        id:"1",
        nombre:"jhon",
        apellido:"romero",
        edad:27
    },
    {
        id:"1",
        nombre:"jhon",
        apellido:"romero",
        edad:27
    },
    {
        id:"1",
        nombre:"jhon",
        apellido:"romero",
        edad:27
    },
    {
        id:"1",
        nombre:"jhon",
        apellido:"romero",
        edad:27
    },
    {
        id:"1",
        nombre:"jhon",
        apellido:"romero",
        edad:27
    },
    {
        id:"1",
        nombre:"jhon",
        apellido:"romero",
        edad:27
    },
    {
        id:"1",
        nombre:"jhon",
        apellido:"romero",
        edad:27
    },
    {
        id:"1",
        nombre:"jhon",
        apellido:"romero",
        edad:27
    },
    {
        id:"1",
        nombre:"jhon",
        apellido:"romero",
        edad:27
    },
    {
        id:"1",
        nombre:"jhon",
        apellido:"romero",
        edad:27
    },
    {
        id:"1",
        nombre:"jhon",
        apellido:"romero",
        edad:27
    },
    {
        id:"1",
        nombre:"jhon",
        apellido:"romero",
        edad:27
    },
    {
        id:"1",
        nombre:"jhon",
        apellido:"romero",
        edad:27
    },
    {
        id:"1",
        nombre:"jhon",
        apellido:"romero",
        edad:27
    },
    {
        id:"1",
        nombre:"jhon",
        apellido:"romero",
        edad:27
    },
    {
        id:"1",
        nombre:"jhon",
        apellido:"romero",
        edad:27
    },
    {
        id:"1",
        nombre:"jhon",
        apellido:"romero",
        edad:27
    },
    {
        id:"1",
        nombre:"jhon",
        apellido:"romero",
        edad:27
    },
    {
        id:"1",
        nombre:"jhon",
        apellido:"romero",
        edad:27
    },
    {
        id:"1",
        nombre:"jhon",
        apellido:"romero",
        edad:27
    },
    {
        id:"1",
        nombre:"jhon",
        apellido:"romero",
        edad:27
    },
    {
        id:"1",
        nombre:"jhon",
        apellido:"romero",
        edad:27
    },
    {
        id:"1",
        nombre:"jhon",
        apellido:"romero",
        edad:27
    },
    {
        id:"1",
        nombre:"jhon",
        apellido:"romero",
        edad:27
    },
    {
        id:"1",
        nombre:"jhon",
        apellido:"romero",
        edad:27
    },
    {
        id:"1",
        nombre:"jhon",
        apellido:"romero",
        edad:27
    },
    {
        id:"1",
        nombre:"jhon",
        apellido:"romero",
        edad:27
    },
    {
        id:"1",
        nombre:"jhon",
        apellido:"romero",
        edad:27
    },
    {
        id:"1",
        nombre:"jhon",
        apellido:"romero",
        edad:27
    },
    {
        id:"1",
        nombre:"jhon",
        apellido:"romero",
        edad:27
    },
    {
        id:"1",
        nombre:"jhon",
        apellido:"romero",
        edad:27
    },
    {
        id:"1",
        nombre:"jhon",
        apellido:"romero",
        edad:27
    },
]

export default data;